// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Turnify.Api.Data;

#nullable disable

namespace Turnify.Api.Migrations
{
    [DbContext(typeof(TurnifyDbContext))]
    [Migration("20260612171459_CambiarA_DateTimeOffset_Mundial")]
    partial class CambiarA_DateTimeOffset_Mundial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Turnify.Api.Models.Citas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodigoVerificacion")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("codigo_verificacion");

                    b.Property<decimal>("CostoDomicilio")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("costo_domicilio");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<int>("DuracionPactadaMin")
                        .HasColumnType("int")
                        .HasColumnName("duracion_pactada_min");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_creacion");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(18, 10)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(18, 10)")
                        .HasColumnName("longitud");

                    b.Property<string>("MetodoRegistro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metodo_registro");

                    b.Property<string>("Modalidad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modalidad");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("PrecioPactado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("precio_pactado");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("proveedor_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("servicio_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("ServicioId");

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("Turnify.Api.Models.Clientes", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool>("activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo")
                        .HasAnnotation("Relational:JsonPropertyName", "activo");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasAnnotation("Relational:JsonPropertyName", "fecha_creacion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre")
                        .HasAnnotation("Relational:JsonPropertyName", "nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono")
                        .HasAnnotation("Relational:JsonPropertyName", "telefono");

                    b.Property<Guid?>("usuario_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id")
                        .HasAnnotation("Relational:JsonPropertyName", "usuario_id");

                    b.HasKey("id");

                    b.HasIndex("usuario_id")
                        .IsUnique()
                        .HasFilter("[usuario_id] IS NOT NULL");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Turnify.Api.Models.HorariosAtencion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int")
                        .HasColumnName("dia_semana");

                    b.Property<TimeSpan>("HoraApertura")
                        .HasColumnType("time")
                        .HasColumnName("hora_apertura");

                    b.Property<TimeSpan>("HoraCierre")
                        .HasColumnType("time")
                        .HasColumnName("hora_cierre");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("proveedor_id");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("horarios_atencion", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "horarios");
                });

            modelBuilder.Entity("Turnify.Api.Models.PlanSuscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("LimiteCitasMes")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrecioMensual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("planes_suscripcion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1a2b3c4-e5f6-4789-90ab-c1d2e3f40001"),
                            Activo = true,
                            LimiteCitasMes = 15,
                            Nombre = "Gratis",
                            PrecioMensual = 0m
                        },
                        new
                        {
                            Id = new Guid("e2f3a4b5-c6d7-4890-a1b2-c3d4e5f60002"),
                            Activo = true,
                            LimiteCitasMes = 9999,
                            Nombre = "Premium",
                            PrecioMensual = 19.99m
                        });
                });

            modelBuilder.Entity("Turnify.Api.Models.Proveedores", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo")
                        .HasAnnotation("Relational:JsonPropertyName", "activo");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("categoria")
                        .HasAnnotation("Relational:JsonPropertyName", "categoria");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ciudad")
                        .HasAnnotation("Relational:JsonPropertyName", "ciudad");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion")
                        .HasAnnotation("Relational:JsonPropertyName", "descripcion");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion")
                        .HasAnnotation("Relational:JsonPropertyName", "direccion");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit")
                        .HasColumnName("eliminado")
                        .HasAnnotation("Relational:JsonPropertyName", "eliminado");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_actualizacion")
                        .HasAnnotation("Relational:JsonPropertyName", "fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasAnnotation("Relational:JsonPropertyName", "fecha_creacion");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre_comercial")
                        .HasAnnotation("Relational:JsonPropertyName", "nombre_comercial");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono")
                        .HasAnnotation("Relational:JsonPropertyName", "telefono");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo")
                        .HasAnnotation("Relational:JsonPropertyName", "tipo");

                    b.Property<bool>("TrabajaDomicilio")
                        .HasColumnType("bit")
                        .HasColumnName("trabaja_domicilio")
                        .HasAnnotation("Relational:JsonPropertyName", "trabaja_domicilio");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id")
                        .HasAnnotation("Relational:JsonPropertyName", "usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Turnify.Api.Models.Roles", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            id = new Guid("6a7fa68f-c28d-4f1b-b2d8-4fb0a6146a43"),
                            nombre = "Administrador"
                        },
                        new
                        {
                            id = new Guid("56992f75-6420-4d55-a5f9-9223248c50d7"),
                            nombre = "Cliente"
                        },
                        new
                        {
                            id = new Guid("8854c07c-6e5e-4876-a29a-c7ad5dcfbab7"),
                            nombre = "Proveedor"
                        },
                        new
                        {
                            id = new Guid("6de2a606-416e-4588-b4eb-cc20856cd80a"),
                            nombre = "SuperAdministrador"
                        });
                });

            modelBuilder.Entity("Turnify.Api.Models.Servicios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Activo")
                        .HasColumnType("int")
                        .HasColumnName("Activo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Categoria");

                    b.Property<decimal>("ComisionPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ComisionPorcentaje");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("DuracionMinutos");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImagenUrl");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Precio");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProveedorId");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("Turnify.Api.Models.Suscripciones", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("suscripciones", (string)null);
                });

            modelBuilder.Entity("Turnify.Api.Models.Usuarios", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "reset_token");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "reset_token_expires");

                    b.Property<bool?>("activo")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "activo");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<bool?>("esta_bloqueado")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:JsonPropertyName", "esta_bloqueado");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "fecha_creacion");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombre");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash")
                        .HasAnnotation("Relational:JsonPropertyName", "password_hash");

                    b.Property<Guid>("rol_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rol_id")
                        .HasAnnotation("Relational:JsonPropertyName", "rol_id");

                    b.Property<DateTime?>("suscripcion_fin")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "suscripcion_fin");

                    b.Property<DateTime?>("ultima_conexion")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "ultima_conexion");

                    b.HasKey("id");

                    b.HasIndex("rol_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Turnify.Api.Models.Citas", b =>
                {
                    b.HasOne("Turnify.Api.Models.Clientes", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Turnify.Api.Models.Proveedores", "Proveedor")
                        .WithMany("Citas")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Turnify.Api.Models.Servicios", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Proveedor");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Turnify.Api.Models.Clientes", b =>
                {
                    b.HasOne("Turnify.Api.Models.Usuarios", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("Turnify.Api.Models.Clientes", "usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Turnify.Api.Models.HorariosAtencion", b =>
                {
                    b.HasOne("Turnify.Api.Models.Proveedores", "Proveedor")
                        .WithMany("Horarios")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Turnify.Api.Models.Proveedores", b =>
                {
                    b.HasOne("Turnify.Api.Models.Usuarios", "Usuario")
                        .WithOne("Proveedor")
                        .HasForeignKey("Turnify.Api.Models.Proveedores", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Turnify.Api.Models.Servicios", b =>
                {
                    b.HasOne("Turnify.Api.Models.Proveedores", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Turnify.Api.Models.Suscripciones", b =>
                {
                    b.HasOne("Turnify.Api.Models.PlanSuscripcion", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turnify.Api.Models.Proveedores", "Proveedor")
                        .WithMany("Suscripciones")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Turnify.Api.Models.Usuarios", b =>
                {
                    b.HasOne("Turnify.Api.Models.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Turnify.Api.Models.Clientes", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Turnify.Api.Models.Proveedores", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Horarios");

                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("Turnify.Api.Models.Usuarios", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("Proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
